#!/usr/bin/env python3
"""gen_firmware.py — generate the ZMK matrix transform + keymap + kscan GPIO map
DIRECTLY from the same model that generates the PCB (deck.py + gen_board.E73_PINMAP),
so firmware and hardware can never drift (the old hand-written 5x10 nice!nano overlay
was stale vs the 9x10 79-key E73 board).

Emits, under firmware/zmk-config/boards/shields/thumbdeck/:
  thumbdeck.dtsi   — kscan (row/col gpios on the E73's real nRF pins) + matrix-transform
  thumbdeck.keymap — one binding per real key, in the transform's order

Electrical matrix (from gen_board.build_matrix): key index i on a grip gets
  row = (i//5) % 9 ,  col = col_off + (i % 5)   (col_off = 0 right, 5 left)
This is index-packed (NOT the 6-wide legend grid), so the transform MUST be generated.
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
import deck
from gen_board import E73_PINMAP, NROWS, NCOLS_HALF

OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..",
      "firmware", "zmk-config", "boards", "arm", "thumbdeck"))

# Ebyte E73-2G4M08S1C pad -> (nRF port, pin), from the official datasheet pin table.
PAD_GPIO = {
    "1": (1,11), "2": (1,10), "3": (0,3), "4": (0,28), "6": (1,13), "7": (0,2),
    "8": (0,29), "9": (0,31), "10": (0,30), "11": (0,0), "12": (0,26), "13": (0,1),
    "14": (0,6), "15": (0,5), "16": (0,8), "17": (1,9), "18": (0,4), "20": (0,12),
    "22": (0,7), "26": (0,18), "28": (0,15), "30": (0,17), "32": (0,20), "33": (0,13),
    "34": (0,22), "35": (0,24), "36": (1,0), "38": (1,2), "40": (1,4), "42": (1,6),
    "43": (0,10),
}

# behaviors that are NOT &kp
SPECIAL = {"FN":"&mo 1", "MB_L":"&mkp LCLK", "MB_R":"&mkp RCLK"}
# &kp <code> aliases for non-obvious legends
KC = {
 "ESC":"ESC","TAB":"TAB","CAP":"CAPS","SHF":"LSHFT","CTL":"LCTRL","WIN":"LGUI","ALT":"LALT",
 "AGR":"RALT","ENT":"RET","BSP":"BSPC","DEL":"DEL","SPC":"SPACE","MEN":"K_APP",
 "`":"GRAVE","'":"SQT",";":"SEMI","/":"FSLH","\\":"BSLH","[":"LBKT","]":"RBKT",",":"COMMA",".":"DOT",
 "F1":"F1","F2":"F2","F3":"F3","F4":"F4","F5":"F5","F6":"F6","F7":"F7","F8":"F8","F9":"F9","F10":"F10",
 "PGUP":"PG_UP","PGDN":"PG_DN",
 "NAV_U":"UP","NAV_D":"DOWN","NAV_L":"LEFT","NAV_R":"RIGHT","NAV_OK":"RET",
}
def kc(lab):
    if lab in SPECIAL: return SPECIAL[lab]
    if lab in KC: return "&kp "+KC[lab]
    if len(lab)==1 and lab.isalpha(): return "&kp "+lab.upper()
    if len(lab)==1 and lab.isdigit(): return "&kp N"+lab
    return "&kp "+lab


def grip_keys(side):
    """Return [(elec_row, elec_col, legend)] for one grip, in placement order."""
    geo = deck.build(deck.Config(side=side))
    col_off = 0 if side == "right" else NCOLS_HALF
    keys = list(geo["keys"]) + [f for f in geo.get("features", []) if f["type"] == "key"]
    out = []
    for i, k in enumerate(keys):
        r = (i // NCOLS_HALF) % NROWS
        c = col_off + (i % NCOLS_HALF)
        out.append((r, c, k.get("label", "?")))
    return out


def main():
    left = grip_keys("left")
    right = grip_keys("right")
    # keymap order: left grip then right grip (both in placement order)
    positions = [("L", *k) for k in left] + [("R", *k) for k in right]

    # kscan gpio lists from E73_PINMAP
    def gpio(net):
        pad = next(p for p, n in E73_PINMAP.items() if n == net)
        port, pin = PAD_GPIO[pad]
        return f"&gpio{port} {pin}"
    rows = [gpio(f"ROW{r}") for r in range(9)]
    cols = [gpio(f"COL{c}") for c in range(10)]

    os.makedirs(OUT, exist_ok=True)
    # ---- thumbdeck.dtsi : kscan + transform ----
    tmap = " ".join(f"RC({r},{c})" for (_g, r, c, _l) in positions)
    row_gpios = "\n".join(f'\t\t\t\t, <{g} (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>' for g in rows)
    row_gpios = row_gpios.replace(", ", "= ", 1) if False else row_gpios
    rowlines = "\n".join(f'\t\t\t\t{"=" if i==0 else ","} <{g} (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>'
                         for i, g in enumerate(rows))
    collines = "\n".join(f'\t\t\t\t{"=" if i==0 else ","} <{g} GPIO_ACTIVE_HIGH>'
                         for i, g in enumerate(cols))
    dtsi = f"""/*
 * thumbdeck.dtsi — GENERATED by hardware/scripts/gen_firmware.py. DO NOT hand-edit.
 * Single 9-row x 10-col col2row matrix on the Ebyte E73-2G4M08S1C (nRF52840).
 * {len(positions)} real keys (right {len(right)} + left {len(left)}); rows shared across
 * both grips over the bridge, cols 0-4 = right grip (local), cols 5-9 = left grip.
 * Row/col GPIO are the E73 pads from gen_board.E73_PINMAP mapped to nRF P0/P1 pins.
 */
#include <dt-bindings/zmk/matrix_transform.h>

/ {{
	chosen {{
		zmk,kscan = &kscan0;
		zmk,matrix_transform = &default_transform;
	}};

	default_transform: keymap_transform_0 {{
		compatible = "zmk,matrix-transform";
		columns = <10>;
		rows = <9>;
		/* one entry per real key, in keymap order (left grip then right grip) */
		map = <
			{tmap}
		>;
	}};

	kscan0: kscan {{
		compatible = "zmk,kscan-gpio-matrix";
		diode-direction = "col2row";
		debounce-press-ms = <8>;
		debounce-release-ms = <8>;

		row-gpios
{rowlines}
			;

		col-gpios
{collines}
			;
	}};
}};
"""
    with open(os.path.join(OUT, "thumbdeck.dtsi"), "w") as f:
        f.write(dtsi)

    # ---- thumbdeck.keymap ----
    binds = []
    for (g, r, c, lab) in positions:
        binds.append(kc(lab))
    # chunk left then right for readability
    def block(items, per):
        return "\n".join("            " + "  ".join(items[i:i+per]) for i in range(0, len(items), per))
    lb = [kc(lab) for (g,r,c,lab) in positions if g == "L"]
    rb = [kc(lab) for (g,r,c,lab) in positions if g == "R"]
    keymap = f"""/*
 * thumbdeck.keymap — GENERATED by hardware/scripts/gen_firmware.py.
 * Bindings are in transform order: all LEFT-grip keys ({len(lb)}) then all RIGHT-grip
 * keys ({len(rb)}). Layer 1 (FN, via the FN key) has BLE-select + bootloader.
 */
#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/outputs.h>

/ {{
	keymap {{
		compatible = "zmk,keymap";
		default_layer {{
			bindings = <
/* LEFT grip ({len(lb)} keys) */
{block(lb, 10)}
/* RIGHT grip ({len(rb)} keys) */
{block(rb, 10)}
			>;
		}};
		fn_layer {{
			bindings = <
{block(["&bt BT_CLR"] + [f"&bt BT_SEL {i}" for i in range(4)] + ["&trans"]*(len(lb)-5), 10)}
{block(["&bootloader","&sys_reset"] + ["&trans"]*(len(rb)-2), 10)}
			>;
		}};
	}};
}};
"""
    with open(os.path.join(OUT, "thumbdeck.keymap"), "w") as f:
        f.write(keymap)

    print(f"generated {len(positions)} keys; rows={rows}; cols={cols}")
    print(f"wrote {OUT}/thumbdeck.dtsi and thumbdeck.keymap")


if __name__ == "__main__":
    main()
